#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libnftnl-soname7
Version  : 1.1.1
Release  : 2
URL      : http://netfilter.org/projects/libnftnl/files/libnftnl-1.1.1.tar.bz2
Source0  : http://netfilter.org/projects/libnftnl/files/libnftnl-1.1.1.tar.bz2
Summary  : Netfilter nf_tables infrastructure library
Group    : Development/Tools
License  : GPL-2.0
Requires: compat-libnftnl-soname7-lib = %{version}-%{release}
Requires: compat-libnftnl-soname7-license = %{version}-%{release}
BuildRequires : pkgconfig(libmnl)

%description
No detailed description available

%package dev
Summary: dev components for the compat-libnftnl-soname7 package.
Group: Development
Requires: compat-libnftnl-soname7-lib = %{version}-%{release}
Provides: compat-libnftnl-soname7-devel = %{version}-%{release}

%description dev
dev components for the compat-libnftnl-soname7 package.


%package lib
Summary: lib components for the compat-libnftnl-soname7 package.
Group: Libraries
Requires: compat-libnftnl-soname7-license = %{version}-%{release}

%description lib
lib components for the compat-libnftnl-soname7 package.


%package license
Summary: license components for the compat-libnftnl-soname7 package.
Group: Default

%description license
license components for the compat-libnftnl-soname7 package.


%prep
%setup -q -n libnftnl-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545404175
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1545404175
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libnftnl-soname7
cp COPYING %{buildroot}/usr/share/package-licenses/compat-libnftnl-soname7/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/libnftnl/batch.h
%exclude /usr/include/libnftnl/chain.h
%exclude /usr/include/libnftnl/common.h
%exclude /usr/include/libnftnl/expr.h
%exclude /usr/include/libnftnl/flowtable.h
%exclude /usr/include/libnftnl/gen.h
%exclude /usr/include/libnftnl/object.h
%exclude /usr/include/libnftnl/rule.h
%exclude /usr/include/libnftnl/ruleset.h
%exclude /usr/include/libnftnl/set.h
%exclude /usr/include/libnftnl/table.h
%exclude /usr/include/libnftnl/trace.h
%exclude /usr/include/libnftnl/udata.h
%exclude /usr/lib64/libnftnl.so
%exclude /usr/lib64/pkgconfig/libnftnl.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnftnl.so.7
/usr/lib64/libnftnl.so.7.3.0

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/compat-libnftnl-soname7/COPYING
