#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libnftnl-soname7
Version  : 1.1.1
Release  : 3
URL      : http://netfilter.org/projects/libnftnl/files/libnftnl-1.1.1.tar.bz2
Source0  : http://netfilter.org/projects/libnftnl/files/libnftnl-1.1.1.tar.bz2
Summary  : Netfilter nf_tables infrastructure library
Group    : Development/Tools
License  : GPL-2.0
Requires: compat-libnftnl-soname7-lib = %{version}-%{release}
Requires: compat-libnftnl-soname7-license = %{version}-%{release}
BuildRequires : pkgconfig(libmnl)
# Suppress generation of debuginfo
%global debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the compat-libnftnl-soname7 package.
Group: Libraries
Requires: compat-libnftnl-soname7-license = %{version}-%{release}

%description lib
lib components for the compat-libnftnl-soname7 package.


%package license
Summary: license components for the compat-libnftnl-soname7 package.
Group: Default

%description license
license components for the compat-libnftnl-soname7 package.


%prep
%setup -q -n libnftnl-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567813602
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1567813602
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libnftnl-soname7
cp COPYING %{buildroot}/usr/share/package-licenses/compat-libnftnl-soname7/COPYING
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/include/libnftnl/batch.h
rm -f %{buildroot}/usr/include/libnftnl/chain.h
rm -f %{buildroot}/usr/include/libnftnl/common.h
rm -f %{buildroot}/usr/include/libnftnl/expr.h
rm -f %{buildroot}/usr/include/libnftnl/flowtable.h
rm -f %{buildroot}/usr/include/libnftnl/gen.h
rm -f %{buildroot}/usr/include/libnftnl/object.h
rm -f %{buildroot}/usr/include/libnftnl/rule.h
rm -f %{buildroot}/usr/include/libnftnl/ruleset.h
rm -f %{buildroot}/usr/include/libnftnl/set.h
rm -f %{buildroot}/usr/include/libnftnl/table.h
rm -f %{buildroot}/usr/include/libnftnl/trace.h
rm -f %{buildroot}/usr/include/libnftnl/udata.h
rm -f %{buildroot}/usr/lib64/libnftnl.so
rm -f %{buildroot}/usr/lib64/pkgconfig/libnftnl.pc

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnftnl.so.7
/usr/lib64/libnftnl.so.7.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-libnftnl-soname7/COPYING
